name: Deployment
on:
  pull_request:
    branches:
      - src
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Packages
        run: yarn install
      - name: Build page
        run: yarn run build
